### ISSUE TITLE
Consider closing error channel as signal to stop

### ISSUE THREAD

**Issue by cameront** [rounds/go-bqstreamer#7]
Thanks for the library guys! Found it tonight and its just about exactly what I'm looking for, though I did run into a couple issues while trying to use it that I though I'd ask about addressing before getting too much deeper.

The first is that it doesn't seem possible to know -- after calling stop() -- that the queue is flushed. This is because the errors channel is never closed, so I assume that clients are just supposed to wait some reasonable amount of time after calling stop?

I also wonder whether there's value in providing the two different interfaces (streamer and multi-streamer). It seems like all you really need is 1 "producer", and N "consumers", and the single streamer is just the N=1 case? I ran into this because I was trying to send to a streamer from multiple goroutines, but that requires me to do my own synchonization around streamer. I finally saw the note that you "probably shouldn't use streamer", but that got me wondering whether both of these issues could be addressed by just changing up the interface to always take a "numWorkers" param, and let the client close the requests channel as a stop-signal, then just iterating over the errors channel to know that the queue is drained.

Not sure if that makes any sense (it's past my bedtime and my brain is fried!) but I've tried to lay it out in code here:
http://play.golang.org/p/qBJ5nofG39

Though I obviously understand if you think that deviates too far from your intended use-cases -- just thought I'd float the idea. Thanks anyway -- this looks very useful!

**Comment by oryband** [comment]
Hey @cameront ! Thank you for providing feedback, and sorry that it took me so long to reply.

1. Yes, the error channel is never closed, and regardless there isn't any direct way to know when flushing to BigQuery happen. Only way now is to wait/sleep until the timeout occurs.
1. Yup, documentation could use a face lift regarding the multi/streamer difference, and the "single" `Streamer` shouldn't really be public at all.

I'm currently working on a "v2" branch that I'll be finalizing in the coming days. It'll introduce breaking changes but will be much clearer and conventional to work with. Some key features include:

1. `sync`/`async` streamer packages. The `async` subpackage will be the old `MultiStreamer` (the "single" `Streamer` will be for internal use only). The `sync` subpackage will feature inserting in sync, waiting for the response before moving on. Practically `async` will use `sync` with goroutines internally.
1. Using interfaces instead of structs, because golang.
1. More tests + mocking.

Feel free to take a look at the branch: https://github.com/rounds/go-bqstreamer/tree/add-sync-streamer

I'll be merging it soon.

Thanks again for the feedback, I'd be happy to hear more in the future.

**Comment by oryband** [comment]
I'd forgot - I'll also take the "flushed" notification channel you requested into account, will keep this issue updated.
